// Income
export const GET_INCOME_START = "GET_INCOME_START";
export const GET_INCOME_SUCCESS = "GET_INCOME_SUCCESS";
export const GET_INCOME_FAILURE = "GET_INCOME_FAILURE";
export const ADD_INCOME_START = "ADD_INCOME_START";
export const ADD_INCOME_SUCCESS = "ADD_INCOME_SUCCESS";
export const ADD_INCOME_FAILURE = "ADD_INCOME_FAILURE";
export const UPDATE_INCOME_START = "UPDATE_INCOME_START";
export const UPDATE_INCOME_SUCCESS = "UPDATE_INCOME_SUCCESS";
export const UPDATE_INCOME_FAILURE = "UPDATE_INCOME_FAILURE";
export const DELETE_INCOME_START = "DELETE_INCOME_START";
export const DELETE_INCOME_SUCCESS = "DELETE_INCOME_SUCCESS";
export const DELETE_INCOME_FAILURE = "DELETE_INCOME_FAILURE";

// Budget
export const GET_BUDGET_START = "GET_BUDGET_START";
export const GET_BUDGET_SUCCESS = "GET_BUDGET_SUCCESS";
export const GET_BUDGET_FAILURE = "GET_BUDGET_FAILURE";
export const ADD_BUDGET_START = "ADD_BUDGET_START";
export const ADD_BUDGET_SUCCESS = "ADD_BUDGET_SUCCESS";
export const ADD_BUDGET_FAILURE = "ADD_BUDGET_FAILURE";
export const UPDATE_BUDGET_START = "UPDATE_BUDGET_START";
export const UPDATE_BUDGET_SUCCESS = "UPDATE_BUDGET_SUCCESS";
export const UPDATE_BUDGET_FAILURE = "UPDATE_BUDGET_FAILURE";
export const DELETE_BUDGET_START = "DELETE_BUDGET_START";
export const DELETE_BUDGET_SUCCESS = "DELETE_BUDGET_SUCCESS";
export const DELETE_BUDGET_FAILURE = "DELETE_BUDGET_FAILURE";

// Savings
export const GET_SAVINGS_START = "GET_SAVINGS_START";
export const GET_SAVINGS_SUCCESS = "GET_SAVINGS_SUCCESS";
export const GET_SAVINGS_FAILURE = "GET_SAVINGS_FAILURE";
export const ADD_SAVINGS_START = "ADD_SAVINGS_START";
export const ADD_SAVINGS_SUCCESS = "ADD_SAVINGS_SUCCESS";
export const ADD_SAVINGS_FAILURE = "ADD_SAVINGS_FAILURE";
export const UPDATE_SAVINGS_START = "UPDATE_SAVINGS_START";
export const UPDATE_SAVINGS_SUCCESS = "UPDATE_SAVINGS_SUCCESS";
export const UPDATE_SAVINGS_FAILURE = "UPDATE_SAVINGS_FAILURE";
export const DELETE_SAVINGS_START = "DELETE_SAVINGS_START";
export const DELETE_SAVINGS_SUCCESS = "DELETE_SAVINGS_SUCCESS";
export const DELETE_SAVINGS_FAILURE = "DELETE_SAVINGS_FAILURE";

// Debt
export const GET_DEBT_START = "GET_DEBT_START";
export const GET_DEBT_SUCCESS = " GET_DEBT_SUCCESS";
export const GET_DEBT_FAILURE = "GET_DEBT_FAILURE";
export const ADD_DEBT_START = "ADD_DEBT_START";
export const ADD_DEBT_SUCCESS = "ADD_DEBT_SUCCESS";
export const ADD_DEBT_FAILURE = "ADD_DEBT_FAILURE";
export const UPDATE_DEBT_START = "UPDATE_DEBT_START";
export const UPDATE_DEBT_SUCCESS = "UPDATE_DEBT_SUCCESS";
export const UPDATE_DEBT_FAILURE = "UPDATE_DEBT_FAILURE";
export const DELETE_DEBT_START = "DELETE_DEBT_START";
export const DELETE_DEBT_SUCCESS = "DELETE_DEBT_SUCCESS";
export const DELETE_DEBT_FAILURE = " DELETE_DEBT_FAILURE";

// Notes
export const GET_NOTES_START = "GET_NOTES_START";
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";
export const GET_NOTES_FAILURE = "GET_NOTES_FAILURE";
export const ADD_NOTES_START = "ADD_NOTES_START";
export const ADD_NOTES_SUCCESS = "ADD_NOTES_SUCCESS";
export const ADD_NOTES_FAILURE = "ADD_NOTES_FAILURE";
export const UPDATE_NOTES_START = "UPDATE_NOTES_START";
export const UPDATE_NOTES_SUCCESS = "UPDATE_NOTES_SUCCESS";
export const UPDATE_NOTES_FAILURE = "UPDATE_NOTES_FAILURE";
export const DELETE_NOTES_START = "DELETE_NOTES_START";
export const DELETE_NOTES_SUCCESS = "DELETE_NOTES_SUCCESS";
export const DELETE_NOTES_FAILURE = "DELETE_NOTES_FAILURE";
